[package]
name = "jmt-proof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jmt-blake3 = "0.1.2"
tokio = "1.14.1"
